name: CI
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image: true

      - name: gradle validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: zsv-cli
          path: build/native/nativeCompile/zsv*
          retention-days: 5